### ISSUE TITLE
Pending TX

### ISSUE THREAD

**Issue by maxmerlin78** [ordimint/web-app#21]
Hello Ordimint Team,

I ordered an OP Return yesterday 22.01.2024 and paid for the fastest option. The TX is still pending! b2afe80ff2d1e82849bcb5fac20c8456a7a2846b6363ee4e34bae9db1940369d

**Comment by ordimint** [comment]
We are sorry for that. We upgrade everything at the moment for Ordimint 2.0. You can paste a Lightning Invoice to refund you. 

But your OP_RETURN is now ready: [mempool.space](https://mempool.space/tx/d9a0e3dc631c29fb0c531215efbcc9d0545b7a805b18b9bd42b28577e081af91)
